### ISSUE TITLE
"raise OSError('could not get source code')" when using the HistoricalRecords() object on a model -> Django 4.1

### ISSUE THREAD

**Issue by jafd08** [jazzband/django-simple-history#1046]
**Describe the bug**
Error on Django 4.1 when using the HistoricalRecords() object on a model. "raise OSError('could not get source code')"

**To Reproduce**
1. Go to any app models.py
2. Create a model
3. create any field (maybe a charfield just to have it there)
4. on the start of the models.py : `from simple_history.models import HistoricalRecords`
5. create the history instance on the model class: `history = HistoricalRecords()`
6. Try to makemigrations or runserver. It throws error: 

> File "/Users/jesuswork/.pyenv/versions/3.9.12/lib/python3.9/inspect.py", line 835, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

7. If you delete the line `history = HistoricalRecords()` and runserver, it won't give any error. The error is there, where the instance of HistoricalRecords is created.

**Expected behavior**
Let me use the command makemigrations- migrate, and runserver. It throws me error on any command (didn't use migrate because makemigrations comes first based on documentation and django use)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] Apple M1 Macbook Pro - Monterrey 12.5.1 (21G83)
 - Django Simple History Version: [e.g. 1.9.1] 3.2 
 - Django Version: [e.g. 1.11.11] 4.1

**Additional context**
Tried to:
1. Tried stable version 3.1.1 , no luck. Updated to 3.2.0 and still same error.
2. Used Mac terminal instead of VS Code terminal, no luck
3. created a new object outside the model, printed it and it was working fine: 
> <simple_history.models.HistoricalRecords object at 0x104eacaf0>

**Comment by jafd08** [comment]
whole error: Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/jesuswork/.pyenv/versions/3.9.12/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/jesuswork/.pyenv/versions/3.9.12/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/django/core/checks/registry.py", line 94, in run_checks
    errors.extend(new_errors)
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/extra_checks/checks/model_checks.py", line 59, in check_models
    yield from check(model, ast=model_ast)
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/extra_checks/checks/base_checks.py", line 40, in __call__
    if not ast or not ast.is_disabled_by_comment(error.id):
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/extra_checks/ast/ast.py", line 112, in is_disabled_by_comment
    return check in self._source_provider.get_disabled_checks_for_line(1)
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/extra_checks/ast/source_provider.py", line 69, in get_disabled_checks_for_line
    self._comments_cache[line_no] = _find_disabled_checks(comments)
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/extra_checks/ast/source_provider.py", line 30, in _find_disabled_checks
    for line in comments:
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/extra_checks/ast/source_provider.py", line 59, in _get_line_comments
    for line in (self.source or "").splitlines()[line_no::-1]:
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/jesuswork/.pyenv/versions/lcos-backend/lib/python3.9/site-packages/extra_checks/ast/source_provider.py", line 45, in source
    return textwrap.dedent(inspect.getsource(self._obj))
  File "/Users/jesuswork/.pyenv/versions/3.9.12/lib/python3.9/inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "/Users/jesuswork/.pyenv/versions/3.9.12/lib/python3.9/inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "/Users/jesuswork/.pyenv/versions/3.9.12/lib/python3.9/inspect.py", line 835, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

**Comment by jafd08** [comment]
seems like extra_checks is causing this error, since it looks for the HistoricalRecords() model and it doesn't exist (because it is dynamic).

Removing extra_checks library should solve this issue.

**Comment by dimk00z** [comment]
@jafd08 thx for the issue, I spent two hours to understand the problem.
