### ISSUE TITLE
m2m_fields throws exception when relation is modified using reverse acessor

### ISSUE THREAD

**Issue by amanz360** [jazzband/django-simple-history#1048]
**Describe the bug**
I'm attempting to use the new `m2m_fields` released in version 3.2.0 but it doesn't appear to handle the m2m related manager on both models properly.

**To Reproduce**
Toy example based on my actual issue

```
class Lot(models.Model):
    pass

class Shipment(models.Model):
    lots = models.ManyToManyField("Lot", related_name="shipments")
    history = HistoricalRecords(m2m_fields=[lots])
```

With this relationship and having generated the appropriate migration after, I ran into an exception when existing code attempted to insert records into the through table via the `shipments` accessor on the Lot model that django would provide
```
Traceback (most recent call last):
  File "/builds/xxx/xxx-server/xxx/tests/test_daily_brand_alert.py", line 383, in test_forecasted_out_of_stock_alerts
    self.lots1.shipments.add(self.shipment1)
  File "/venvs/xxx/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 950, in add
    self._add_items(
  File "/venvs/xxx/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 1159, in _add_items
    signals.m2m_changed.send(
  File "/venvs/xxx/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/venvs/xxx/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/venvs/xxx/lib/python3.9/site-packages/simple_history/models.py", line 637, in m2m_changed
    self.create_historical_record(instance, "~")
  File "/venvs/xxx/lib/python3.9/site-packages/simple_history/models.py", line 698, in create_historical_record
    self.create_historical_record_m2ms(history_instance, instance)
  File "/venvs/xxx/lib/python3.9/site-packages/simple_history/models.py", line 643, in create_historical_record_m2ms
    through_model = getattr(original_instance, field.name).through
AttributeError: 'Lot' object has no attribute 'lots'
```

**Expected behavior**
I'd expect defining the `m2m_fields` on one model to record changes made via the corresponding model without exception

**Comment by amanz360** [comment]
Noting an obvious workaround is to only call the ManyToMany related manager in one direction, this is the solution I'm using for now.

**Comment by michaeljaszczuk** [comment]
Have you created and ran migrations?

**Comment by andweb-lawcode** [comment]
I am facing a similar issue;

Setup to reproduce:

```
class TestUser(models.Model):
    pass

class Company(models.Model):
    contacts = models.ManyToManyField(TestUser, related_name="contact_in_companies")
    history = HistoricalRecords(m2m_fields=[contacts])
```

migrations were created and run.

run:

```
user = TestUser()
user.save()
company = Company()
company.save()
user.contact_in_companies.add(company)
```

throws the following error:

```
AttributeError                            Traceback (most recent call last)
Cell In[12], line 1
----> 1 user.contact_in_companies.add(company)

File xxx/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py:950, in create_forward_many_to_many_manager.<locals>.ManyRelatedManager.add(self, through_defaults, *objs)
    948 db = router.db_for_write(self.through, instance=self.instance)
    949 with transaction.atomic(using=db, savepoint=False):
--> 950     self._add_items(
    951         self.source_field_name, self.target_field_name, *objs,
    952         through_defaults=through_defaults,
    953     )
    954     # If this is a symmetrical m2m relation to self, add the mirror
    955     # entry in the m2m table.
    956     if self.symmetrical:

File xxx/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py:1159, in create_forward_many_to_many_manager.<locals>.ManyRelatedManager._add_items(self, source_field_name, target_field_name, through_defaults, *objs)
   1150 self.through._default_manager.using(db).bulk_create([
   1151     self.through(**through_defaults, **{
   1152         '%s_id' % source_field_name: self.related_val[0],
   (...)
   1155     for target_id in missing_target_ids
   1156 ], ignore_conflicts=can_ignore_conflicts)
   1158 if must_send_signals:
-> 1159     signals.m2m_changed.send(
   1160         sender=self.through, action='post_add',
   1161         instance=self.instance, reverse=self.reverse,
   1162         model=self.model, pk_set=missing_target_ids, using=db,
   1163     )

File xxx/lib/python3.9/site-packages/django/dispatch/dispatcher.py:180, in Signal.send(self, sender, **named)
    177 if not self.receivers or self.sender_receivers_cache.get(sender) is NO_RECEIVERS:
    178     return []
--> 180 return [
    181     (receiver, receiver(signal=self, sender=sender, **named))
    182     for receiver in self._live_receivers(sender)
    183 ]

File xxx/lib/python3.9/site-packages/django/dispatch/dispatcher.py:181, in <listcomp>(.0)
    177 if not self.receivers or self.sender_receivers_cache.get(sender) is NO_RECEIVERS:
    178     return []
    180 return [
--> 181     (receiver, receiver(signal=self, sender=sender, **named))
    182     for receiver in self._live_receivers(sender)
    183 ]

File xxx/lib/python3.9/site-packages/simple_history/models.py:663, in HistoricalRecords.m2m_changed(self, instance, action, attr, pk_set, reverse, **_)
    659     return
    661 if action in ("post_add", "post_remove", "post_clear"):
    662     # It should be safe to ~ this since the row must exist to modify m2m on it
--> 663     self.create_historical_record(instance, "~")

File xxx/lib/python3.9/site-packages/simple_history/models.py:710, in HistoricalRecords.create_historical_record(self, instance, history_type, using)
    706 history_user = self.get_history_user(instance)
    707 history_change_reason = self.get_change_reason_for_object(
    708     instance, history_type, using
    709 )
--> 710 manager = getattr(instance, self.manager_name)
    712 attrs = {}
    713 for field in self.fields_included(instance):

AttributeError: 'TestUser' object has no attribute 'history'
```

as @amanz360 pointed out, modifying the relation through Company.contacts works.

django-simple-history v3.5, django 3.2.19
