### ISSUE TITLE
DoesNotExist model when deleting through Django Admin

### ISSUE THREAD

**Issue by rondanen** [jazzband/django-simple-history#1112]
**Describe the bug**
Recently realized we get an error `Model. DoesNotExist` when deleting entries with simple history. Probably related to 3.2.0

**To Reproduce**
1. Go to any Django admin page with SimpleHistoryAdmin
3. Click on an entry
4. Click delete
5. Confirm on "Yes, I'm sure"
6. You now see the error

**Expected behavior**
Delete the object without any error.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - OS: macOS 12.2.1 and Amazon Linux 2/3.4.3 
 - Browser (if applicable): chrome
 - Django Simple History Version: 3.2.0
 - Django Version: 3.2.16
 - Database Version: PostgreSQL 12.11 and 13.0

**Additional context**
Traceback:
```
Traceback (most recent call last):
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1851, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1881, in _delete_view
    self.delete_model(request, obj)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1105, in delete_model
    obj.delete()
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
    return collector.delete()
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/db/models/deletion.py", line 435, in delete
    signals.post_delete.send(
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/simple_history/models.py", line 622, in post_delete
    self.create_historical_record(instance, "-", using=using)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/simple_history/models.py", line 673, in create_historical_record
    attrs[field.attname] = getattr(instance, field.attname)
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/db/models/query_utils.py", line 144, in __get__
    instance.refresh_from_db(fields=[field_name])
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/db/models/base.py", line 650, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "/Python/Projects/MyProject-backend/venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
MyProject.accounting.models.invoice.Invoice.DoesNotExist: Invoice matching query does not exist.
```

**Comment by rondanen** [comment]
It turns out that, in the Admin view, we used a custom `get_queryset() `with `only()` and excluded some foreign keys. Thefore, when deleting an entry, django-simple-history couldn't find some attributes and crashed.
