### ISSUE TITLE
Admin view needs `has_view_permission` in context for Django 2.1

### ISSUE THREAD

**Issue by kut** [jazzband/django-simple-history#443]
**Describe the bug**
We get a `KeyError` when trying to view a historical object via the admin, because the key `'has_view_permission'` does not exist. This is because Django 2.1 adds a `has_view_permission` to the context for rendering. [See here](https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.has_view_permission)

**To Reproduce**
1. Use Django>=2.1
2. Go to any historical object in the admin (e.g. `/admin/content/post/123/history/4`)
3. KeyError is the result

**Expected behavior**
Should display the historical object.

**Environment:**
 - OS: All
 - Django Simple History Version: 2.3 and 2.4
 - Django Version: 2.1+
 - Database Version: MySQL 5.7.23

**Comment by shlywa** [comment]
I can't seem to reproduce this with the current django-simple-history version. Do you have a repo that reproduces it?

**Comment by rossmechanic** [comment]
Maybe it's a MySQL issue? We've seen a few of those...

**Comment by kut** [comment]
Very bizarre - I found the `KeyError` occurs only when the admin class has `save_on_top = True`.

I'm attaching my stack trace below, but it looks like when `save_on_top = True`, an additional block is included in the template, which calls the tag `submit_row`, on line 48 of `admin_modify.py`. Inside this function, `has_view_permission = context['has_view_permission']` is what raises the `KeyError`.

```
ERROR Internal Server Error: /brain/research/searchtemplate/70a77a3a-995e-4f97-8741-815a5e765951/history/70/
Traceback (most recent call last):
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\simple_history\admin.py", line 194, in history_form_view
    **extra_kwargs)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\contrib\admin\templatetags\admin_modify.py", line 60, in submit_row
    has_view_permission = context['has_view_permission']
  File "C:\Environments\Python3EnvVisor\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'has_view_permission'
```

**Comment by barm** [comment]
Ah nice, that's helpful. We'll take another look!

**Comment by erikvw** [comment]
What I am proposing / working on in PR #529 might address this.

**Comment by john-parton** [comment]
I can confirm that the issue only appears with `save_on_top = True`.

Setting `save_on_top = False` works around the issue for me.

**Comment by john-parton** [comment]
@barm I have a minimal fix in a PR. 

Only needed to change 4 lines
